FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY auth.html /usr/share/nginx/html/auth.html
COPY recruiter.html /usr/share/nginx/html/recruiter.html
COPY careerpredictor.html /usr/share/nginx/html/careerpredictor.html
COPY careerpredictor.html.html /usr/share/nginx/html/careerpredictor.html.html

EXPOSE 80
